### ISSUE TITLE
implement autotools plugin

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#15]
depends on #11 
the plugin should:
- [ ] set spec.build, spec.install
- [ ] append spec.required_files, spec.buildrequired_files

**Comment by jsilhan** [comment]
There are no good resource how you can get dependencies out of `./configure`. Autotools [1] is similar to cmake - which you are familiar with.

This is the example of project using autotools [2] and there's the dependency definition [3].
 Pure regexp matching won;t work well as there could be variables too. This is a research topic.
[1] http://www.gnu.org/software/automake/manual/html_node/Dependency-Tracking.html
[2] https://github.com/rpm-software-management/libhif
[3] https://github.com/rpm-software-management/libhif/blob/master/configure.ac#L90

**Comment by LukasSlouka** [comment]
How do we want to treat optional and alternative modules? I cant really determine if the optional module will in fact be needed, so I assume we have to add it to dependencies anyway. Do we add all alternatives as well? It is easier option since i can treat all `PKG_CHECK_MODULES` macros the same way not checking where it is actually placed within the `configure.ac` file.

**Comment by jsilhan** [comment]
You can do it as you wish. we can improve it later.
