### ISSUE TITLE
UX: prefill the spec.Name, version, ... what can be found by project builder plugins

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#295]
- [ ] maven plugin
- [ ] cmake plugin
- [ ] autotools
- [ ] setuptools
- [ ] document `extracted` plugin phase that it could change Spec required fields and in other methods it's forbidden to do that. - add it as some yellow / blue notice, please

It should be added to spec in `extracted` method

depends on #280 for fully working but can be implemented simultaneously

**Comment by LukasSlouka** [comment]
By the way I thought it would be nice to add simple control for `version` field on this page, because version cannot contain `dash` character, and user might not be familiar with it and later his RPM would not build because of it which would cause confusion. I noticed it when I extracted version with maven and it read `1.0-SNAPSHOT` which I just ignored, later the build crashed because of it. 

For rpm naming rules see [this](http://www.rpm.org/max-rpm/ch-rpm-file-format.html)

**Comment by LukasSlouka** [comment]
If it is added in `patched` phase, then it would not show up in `mandatory page` and that might be a problem because those extracted information are not so reliable in my opinion. I thought it would be just suggestion for user to consider and change if needed. 

I thought we would add `extracted` method to these plugins, because files that contain information we want to prefill are present right after extraction.

**Comment by jsilhan** [comment]
yes, the plugins should run in `extracted` - that was a typo. Fixed.
